#!/usr/bin/env bun
/**
 * This script inlines JSON theme files into a TypeScript file
 * to work around Bun's --compile limitation with JSON imports
 */

import { readdir, readFile, writeFile } from "fs/promises"
import { join, basename } from "path"

const THEME_DIR = join(import.meta.dir, "../src/cli/cmd/tui/context/theme")
const OUTPUT_FILE = join(import.meta.dir, "../src/cli/cmd/tui/context/theme-data.ts")

async function main() {
  const files = await readdir(THEME_DIR)
  const jsonFiles = files.filter(f => f.endsWith(".json"))

  const imports: string[] = []
  const exports: string[] = []

  for (const file of jsonFiles) {
    const content = await readFile(join(THEME_DIR, file), "utf-8")
    const themeName = basename(file, ".json")
    const varName = themeName.replace(/-/g, "_")
    imports.push(`const ${varName} = ${content}`)
    exports.push(`  "${themeName}": ${varName},`)
  }

  const output = `// Auto-generated file - do not edit manually
// Generated by scripts/inline-json.ts

${imports.join("\n\n")}

export const THEME_DATA = {
${exports.join("\n")}
}
`

  await writeFile(OUTPUT_FILE, output)
  console.log(`Generated ${OUTPUT_FILE} with ${jsonFiles.length} themes`)
}

main().catch(console.error)
